[package]
name = "prime_generator"
version = "0.1.2"
authors = ["Michael Berry <trismegustis@gmail.com>"]
edition = "2018"

[lib]
name = "primes"
path = "src/lib.rs"

[[bin]]
name = "prime-generator"
path = "src/prime-generator.rs"

[dependencies]
clap = "2.33.0"
termcolor = "1.1"
